// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKf1oCDXZAdOLp6OcUv3znPqnLmUZe-5I',
    appId: '1:1069966275674:android:05e0c6d65d9359820c1463',
    messagingSenderId: '1069966275674',
    projectId: 'notes-project-flutter-tutorial',
    storageBucket: 'notes-project-flutter-tutorial.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBi0h32elRNx1vV_Ig1ofRB-ox2vAXUxoM',
    appId: '1:1069966275674:ios:194cb268a5f221980c1463',
    messagingSenderId: '1069966275674',
    projectId: 'notes-project-flutter-tutorial',
    storageBucket: 'notes-project-flutter-tutorial.firebasestorage.app',
    iosBundleId: 'com.simon.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBi0h32elRNx1vV_Ig1ofRB-ox2vAXUxoM',
    appId: '1:1069966275674:ios:194cb268a5f221980c1463',
    messagingSenderId: '1069966275674',
    projectId: 'notes-project-flutter-tutorial',
    storageBucket: 'notes-project-flutter-tutorial.firebasestorage.app',
    iosBundleId: 'com.simon.notesApp',
  );
}
